-- ============================================================
-- AI Matchmaker - Finalized Data Model (PostgreSQL)
-- ============================================================
-- Reflects ALL confirmed decisions through the back-office round.
--
-- IDENTITY & FLOW
--   - UUID primary keys throughout.
--   - No "session" concept: one user = one lifelong flow. Flow
--     position lives directly on the user.
--   - Returning users always resume the same flow in place (same
--     task, same user-message count). No TTL, no restart.
--
-- TASKS & PROGRESSION
--   - A task closes after the USER sends the Nth message, where N
--     is the task's max_user_messages cap. The AI's response to
--     that Nth message is the closing message.
--   - Closing is also triggered by the evaluation prompt returning
--     END_TASK. A cap hit closes the task regardless of evaluation.
--   - On close, the whisperer is skipped and the speaker runs with
--     {{whisperer}} bound to the task's end_message instruction
--     (the end_message steers the speaker; it is NOT sent verbatim).
--   - The LAST task, on close, sets users.completed_at and the user
--     is moved to the done/redirect state.
--   - The very FIRST AI message of the whole flow is a single
--     scripted opener stored in CONFIG (flow_opener), NOT per task.
--     Every other task's first message is generated by the speaker.
--   - Tasks are never hard-deleted: is_active=false removes them
--     from future progression while keeping the row for replay and
--     letting in-flight users finish the task they're on.
--   - Task ORDER is set ONLY by drag-and-drop (the `position`
--     field). There is no typed order field in the task editor.
--
-- VERSIONING
--   - ONE snapshot of the entire prompt config (all prompts +
--     tasks + parts + flow_opener) per "Save & publish".
--   - Editor edits are DRAFT (live tables) until published. Cancel
--     restores live tables from the last snapshot. Reload restores
--     a chosen snapshot into the live tables. Single draft,
--     last-save-wins (single-admin for now).
--   - Each prompt_results row stamps the config_version_id that
--     was live when it executed -> full reproducibility.
--
-- OTHER
--   - Conversation data retained indefinitely (for now).
--   - Profile-fact extraction deferred (no profile columns yet).
--   - Media linked to BOTH user and the turn it appeared in.
--     Outbound (AI) photos ride on the speaker turn.
-- ============================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";  -- for gen_random_uuid()

-- Tables are defined in dependency order (referenced before
-- referencing) so foreign keys resolve at creation time:
--   config_versions -> tasks -> users -> turns -> prompt_results -> media
-- plus the standalone live-config tables (prompts, parts).


-- ============================================================
-- CONFIG VERSION SNAPSHOTS (IMMUTABLE)
-- Each "Save & publish" writes ONE snapshot of the entire config
-- (all prompts + tasks + parts + flow_opener) as a single
-- immutable row. Turns stamp config_version_id. "Reload" copies a
-- snapshot's contents back into the live editor tables.
-- ============================================================
CREATE TABLE config_versions (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

    -- Full snapshot captured at publish time, as one atomic record:
    --   { "prompts": [...], "parts": [...], "tasks": [...],
    --     "flow_opener": "..." }
    -- Source of truth a turn reproduces against, and what "reload"
    -- restores from.
    snapshot        jsonb       NOT NULL,

    label           text,                        -- optional human label
    published_by    text,                        -- admin identifier
    published_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_config_versions_published ON config_versions (published_at DESC);


-- ============================================================
-- PROMPT CONFIG - LIVE (DRAFT) TABLES
-- The current editable state the admin works on. Edits here are
-- DRAFT until "Save & publish" snapshots them into config_versions.
-- "Cancel" restores these from the latest snapshot.
-- ============================================================

-- The four pipeline prompts. Exactly four rows, one per type.
CREATE TABLE prompts (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    prompt_type     text        NOT NULL UNIQUE, -- 'speaker'|'whisperer'|'detection'|'evaluation'
    body            text        NOT NULL,
    model           text        NOT NULL,        -- per-prompt model selection (dropdown)
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Reusable text snippets injected as {{part_name}}. A part body may
-- itself reference {{other_part}} (resolved during rendering).
CREATE TABLE parts (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name            text        NOT NULL UNIQUE, -- referenced as {{name}}
    body            text        NOT NULL,
    updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Admin-created task DEFINITIONS (the shared config, same for all users). The
-- per-user EXECUTION of a task is a row in the `tasks` instance table (Step B).
-- Order is the `position` field, set ONLY by the drag-and-drop reorder view.
CREATE TABLE task_types (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    name                text        NOT NULL,

    -- Drag-and-drop order. Mutated by the reorder view only.
    position            integer     NOT NULL,

    -- Soft-delete: false removes the task from future progression
    -- but keeps the row (replay still resolves; in-flight users on
    -- this task finish it). Progression filters to is_active = true.
    is_active           boolean     NOT NULL DEFAULT true,

    instruction         text        NOT NULL,    -- {{task_instruction}}
    evaluation          text,                    -- {{task_evaluation}}
    initial_thought     text,                    -- {{initial_thought_instruction}} (per-task)

    -- Steers the speaker on close: bound to {{whisperer}} when the
    -- task closes. NOT sent to the user verbatim.
    end_message         text,

    -- Cap on USER messages. Task closes after the user sends this
    -- many messages (the AI's reply to the Nth is the closing msg).
    max_user_messages   integer,

    -- Future candidate-picker seam: when true, an algorithm runs at
    -- the START of this task to pick an attachment/candidate.
    -- Unused for now; the column is just the seam.
    has_pretask_hook    boolean     NOT NULL DEFAULT false,

    updated_at          timestamptz NOT NULL DEFAULT now()

    -- NOTE: position is intentionally NOT UNIQUE-constrained at the
    -- DB level. Drag-and-drop reordering rewrites multiple rows'
    -- positions in one transaction; a UNIQUE constraint would fight
    -- mid-swap states. Uniqueness is maintained by the reorder logic.
);

CREATE INDEX idx_task_types_position ON task_types (position) WHERE is_active;


-- ------------------------------------------------------------
-- USERS
-- The person, keyed on normalized E.164 phone.
-- A user IS the flow: their position in the task flow lives here.
-- ------------------------------------------------------------
CREATE TABLE users (
    id                              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),

    phone_e164                      text        NOT NULL UNIQUE, -- canonical +1XXXXXXXXXX
    phone_verified_at               timestamptz,                 -- set when SMS code confirmed

    -- Flow position. current_task_id NULL = flow not yet started
    -- (only the scripted flow_opener has been sent, awaiting first
    -- user reply).
    current_task_id                 uuid        REFERENCES task_types(id),

    -- Counts USER messages within the current task. Reset to 0 when
    -- advancing to a new task. When it reaches the task's
    -- max_user_messages cap, that turn closes the task.
    current_task_user_message_count integer     NOT NULL DEFAULT 0,

    -- Set when the LAST task closes; user is then moved to the
    -- done/redirect state. NULL = flow still in progress.
    completed_at                    timestamptz,

    last_activity_at                timestamptz NOT NULL DEFAULT now(), -- analytics only
    created_at                      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_users_phone ON users (phone_e164);
CREATE INDEX idx_users_current_task ON users (current_task_id);

-- Per-user task EXECUTION instances. task_types = definitions (shared);
-- tasks = one row per (user, task_type) run, carrying the status/outcome.
--   started   -> opened, not finished
--   completed -> ended via [END_TASK] or cap hit (neutral)
--   accepted  -> ended via [ACCEPT]
--   refused   -> ended via [REFUSE]
CREATE TABLE tasks (
    id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid        NOT NULL REFERENCES users(id),
    task_type_id  uuid        NOT NULL REFERENCES task_types(id),
    status        text        NOT NULL DEFAULT 'started'
                    CHECK (status IN ('started','completed','accepted','refused')),
    started_at    timestamptz NOT NULL DEFAULT now(),
    decided_at    timestamptz,
    UNIQUE (user_id, task_type_id)
);
CREATE INDEX idx_tasks_user ON tasks (user_id);


-- ------------------------------------------------------------
-- TURNS
-- One exchange in a user's single conversation. Append-only,
-- ordered by seq per user. This ordered log is what resume and
-- back-office replay rebuild from.
-- ------------------------------------------------------------
CREATE TABLE turns (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    seq             integer     NOT NULL,        -- 1,2,3... within this user

    -- Inbound user text. NULL for an AI-initiated message with no
    -- preceding user input (e.g. the scripted flow opener, or the
    -- next task's first message at a boundary).
    user_message    text,

    -- Task active when this turn ran (denormalized for replay
    -- grouping and per-task analytics; the "new task" divider in
    -- replay is drawn where this value changes between turns).
    task_id         uuid        REFERENCES task_types(id),

    created_at      timestamptz NOT NULL DEFAULT now(),

    UNIQUE (user_id, seq)
);

CREATE INDEX idx_turns_user ON turns (user_id, seq);


-- ------------------------------------------------------------
-- PROMPT_RESULTS
-- One row per prompt EXECUTION within a turn (up to 4 per turn:
-- detection, evaluation, whisperer, speaker). Powers the
-- back-office "see completion" view.
-- ------------------------------------------------------------
CREATE TABLE prompt_results (
    id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    turn_id             uuid        NOT NULL REFERENCES turns(id) ON DELETE CASCADE,

    prompt_type         text        NOT NULL,    -- 'detection'|'evaluation'|'whisperer'|'speaker'

    -- The exact prompt sent to the model with all {{variables}} and
    -- {% if %} conditions resolved. This is what "see completion"
    -- displays. On a closing turn the speaker's resolved_prompt
    -- shows the task end_message in the {{whisperer}} slot.
    resolved_prompt     text        NOT NULL,

    output              text,                    -- model output; for speaker, the AI message

    -- Observability for the error/skip policies:
    --   'ok'        normal
    --   'error'     call failed (and was not recovered)
    --   'fallback'  failed but degraded gracefully
    --               (evaluation->CONTINUE, detection->none,
    --                whisperer->empty hint, speaker->retry/canned)
    --   'skipped'   intentionally not run (whisperer on a closing
    --               turn; the speaker uses end_message instead)
    status              text        NOT NULL DEFAULT 'ok',
    fell_back_to        text,                    -- e.g. 'CONTINUE' when evaluation errored

    model               text,                    -- model id actually used, e.g. 'gpt-4.1-mini'

    -- Stamps the ENTIRE config state live when this executed. One
    -- pointer = full reproducibility (a version is a whole snapshot).
    -- Replay shows this per turn, so mid-conversation publishes are
    -- visible (early turns v13, later turns v14, etc.).
    config_version_id   uuid        NOT NULL REFERENCES config_versions(id),

    latency_ms          integer,                 -- optional per-call timing
    seq_in_turn         integer,                 -- execution order within a turn (deterministic display)
    task_id             uuid,                    -- the task this result ran under (transitions are intra-turn)
    created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_prompt_results_turn ON prompt_results (turn_id);


-- ------------------------------------------------------------
-- MEDIA
-- Images. Linked to the user (whose photos) AND to the turn it
-- appeared in (replay shows it inline at the right spot).
-- Outbound AI photos ride on the speaker turn. turn_id NULL is
-- allowed for media not tied to a message.
-- ------------------------------------------------------------
CREATE TABLE media (
    id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    turn_id         uuid        REFERENCES turns(id) ON DELETE SET NULL,

    direction       text        NOT NULL,        -- 'inbound' (user) | 'outbound' (AI)
    url             text        NOT NULL,         -- storage location (S3/GCS/etc.)
    mime_type       text,
    width           integer,
    height          integer,

    created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_media_user ON media (user_id);
CREATE INDEX idx_media_turn ON media (turn_id);


-- ============================================================
-- KEY FLOWS (reference)
-- ============================================================
-- ENTRY:
--   Phone field -> validate E.164 -> SMS verify (dev bypass: code
--   '000' ONLY when env=development) -> find-or-create user by
--   phone -> issue session cookie -> send scripted flow_opener
--   (a turn with NULL user_message) -> await first user reply.
--
-- RESUME (returning phone, always):
--   Look up user by phone_e164; read current_task_id +
--   current_task_user_message_count; rebuild history from turns
--   (by seq); continue in place. No TTL, no restart.
--
-- TURN LOOP (every inbound user message):
--   acquire per-user lock (reject if busy) -> persist turn,
--   increment user-message count -> detection + evaluation
--   concurrently -> join -> closing? (END_TASK or count >= cap):
--     continuing: whisperer runs -> speaker streams ({{whisperer}}
--                 = hint)
--     closing:    skip whisperer -> speaker streams ({{whisperer}}
--                 = end_message) -> advance to next ACTIVE task
--                 (count -> 0); if none, set completed_at + redirect
--   -> persist results (+ config_version_id) -> release lock.
--
-- PUBLISH:  serialize live prompts+parts+tasks+flow_opener to JSONB
--           -> INSERT config_versions -> new turns stamp it.
-- CANCEL:   overwrite live tables from latest snapshot.
-- RELOAD:   overwrite live tables from chosen snapshot, then publish.
-- ============================================================
